### ISSUE TITLE
如何使用？

### ISSUE THREAD

**Issue by lowerbound123** [Minxyzgo/MiraiGoChess#1]
请问这个插件使用的命令是什么呢？

**Comment by Minxyzgo** [comment]
很抱歉很久没有看Github了，你可以在任何机器人所在的群聊中输入 .帮助 来查看命令指南

**Comment by Minxyzgo** [comment]
注: 还需在终端中使用 `enableGroup add 群号`来添加可使用的群。
类似的还有
 `enableGroup remove 群号`删除群
 `enableGroup list`列出所有群

**Comment by Minxyzgo** [comment]
另外，由于插件还是半成品，要获得完美体验还需要在源代码下的`KotinMain.kt`中手动修改`masterId`为主人QQ号，`katagoPath, enableKatago, configPath`后自行编译。我可能会在暑假完善这个插件

**Comment by lowerbound123** [comment]
非常感谢，等您更新
